[package]
name = "local_forc"
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
forc = "0.19.2"
tokio = "1.20.0"
