[package]
name = "test_abigen"
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc_macro = true

[dependencies]
fuels-core = { git = "https://github.com/FuelLabs/fuels-rs" }
proc-macro2 = "1.0"
syn = "1.0.12"
test_macros = { path = "../test_macros" }
