name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    types: [ opened, synchronize, reopened, labeled, unlabeled ]
  release:
    types: [ published ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  RUST_VERSION: 1.84.1
  FORC_VERSION: 0.66.6
  FUEL_CORE_VERSION: 0.41.4

jobs:
  compile-sway:
    name: Compile Sway Projects
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install fuelup
        run: |
          curl -fsSL https://install.fuel.network/ | sh -s -- --skip-toolchain-installation --no-modify-path
          echo "$HOME/.fuelup/bin" >> $GITHUB_PATH

      - name: Install fuel toolchain and forc
        run: |
          fuelup toolchain new custom
          fuelup component add "forc@${FORC_VERSION}"
      
      - name: Check Sway project formatting
        run: forc fmt --check

      - name: Build Sway projects
        run: forc build --release

      - name: Upload compiled Sway projects
        uses: actions/upload-artifact@v4
        with:
          name: sway-artifacts
          path: sway/**/*.bin

  cargo-check:
    name: cargo check --tests
    runs-on: ubuntu-latest
    needs: compile-sway
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download Sway artifacts
        uses: actions/download-artifact@v4
        with:
          name: sway-artifacts

      - name: Run cargo check --tests
        run: cargo check --tests

  cargo-clippy:
    name: cargo clippy --tests
    runs-on: ubuntu-latest
    needs: compile-sway
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download Sway artifacts
        uses: actions/download-artifact@v4
        with:
          name: sway-artifacts

      - name: Run cargo clippy --tests
        run: cargo clippy --tests

  cargo-test:
    name: cargo test (TARGET_CHAIN="local")
    runs-on: ubuntu-latest
    needs: compile-sway
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download Sway artifacts
        uses: actions/download-artifact@v4
        with:
          name: sway-artifacts

      - name: Install fuelup
        run: |
          curl -fsSL https://install.fuel.network/ | sh -s -- --skip-toolchain-installation --no-modify-path
          echo "$HOME/.fuelup/bin" >> $GITHUB_PATH

      - name: Install fuel-core
        run: |
          fuelup toolchain new custom
          fuelup component add fuel-core@${FUEL_CORE_VERSION}

      - name: Run cargo test with local node
        run: |
          export TARGET_CHAIN="local"
          cargo test
